#!/usr/bin/python

import pygame
import sys

SCREEN_WIDTH = 1020
SCREEN_HEIGHT = 720
PIXEL_HEIGHT = 240

def getIScreenDimensions(screenWidth, screenHeight):
    iScreenHeight = PIXEL_HEIGHT + ((screenHeight % PIXEL_HEIGHT) / (screenHeight / PIXEL_HEIGHT))
    iScreenWidth = screenWidth / (screenHeight / PIXEL_HEIGHT)
    return iScreenWidth, iScreenHeight

def flipDisplay(iScreen, screen):
    #terribly inefficient, will fix later
    screen.blit(pygame.transform.scale(iScreen, [ \
        iScreen.get_width() * (screen.get_height() / PIXEL_HEIGHT), \
        (iScreen.get_height() * (screen.get_height() / PIXEL_HEIGHT)) \
        ]), [ \
        (screen.get_width() - (iScreen.get_width() * (screen.get_height() / PIXEL_HEIGHT))) / 2, \
        (screen.get_height() - (iScreen.get_height() * (screen.get_height() / PIXEL_HEIGHT))) / 2 \
        ])
    pygame.display.flip()

def main():
    quit = False
    pygame.init()
    screen = pygame.display.set_mode([SCREEN_WIDTH, SCREEN_HEIGHT])
    clock = pygame.time.Clock()
    iScreenWidth, iScreenHeight = getIScreenDimensions(screen.get_width(), screen.get_height())
    iScreen = pygame.Surface([iScreenWidth, iScreenHeight])
    grassImage = pygame.image.load('images/tiles/grass.png').convert_alpha()

    while not quit:
        time_passed = clock.tick(50)
        for event in pygame.event.get():
            if event.type == pygame.QUIT: quit = True
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_q: pygame.event.post(pygame.event.Event(pygame.QUIT))
        y = 0
        while y <= iScreen.get_height() / 10:
           x = 0
           while x <= iScreen.get_width() / 10:
               iScreen.blit(grassImage, [x * 10, y * 10])
               x += 1
           y += 1

        flipDisplay(iScreen, screen)

    sys.exit()

main()
