#!/usr/bin/python

import pygame
import sys
from hackmap import hackmap

#defaults, all of this gets set in setup_screen
SCREEN_WIDTH = 1020
SCREEN_HEIGHT = 720
PIXEL_HEIGHT = 240
PIXEL_RATIO = 1
ISCREEN_WIDTH = 320
ISCREEN_HEIGHT = 240
SCREEN_X_OFFSET = 0
SCREEN_Y_OFFSET = 0

def setup_screen(width, height):
    global SCREEN_WIDTH
    global SCREEN_HEIGHT
    global PIXEL_RATIO
    global ISCREEN_HEIGHT
    global ISCREEN_WIDTH
    global SCREEN_X_OFFSET
    global SCREEN_Y_OFFSET
    SCREEN_WIDTH = width
    SCREEN_HEIGHT = height
    PIXEL_RATIO = height / PIXEL_HEIGHT
    ISCREEN_HEIGHT = PIXEL_HEIGHT + ((height % PIXEL_HEIGHT) / PIXEL_RATIO)
    ISCREEN_WIDTH = width / PIXEL_RATIO
    SCREEN_X_OFFSET = (SCREEN_WIDTH - (ISCREEN_WIDTH * PIXEL_RATIO)) / 2
    SCREEN_Y_OFFSET = (SCREEN_HEIGHT - (ISCREEN_HEIGHT * PIXEL_RATIO)) / 2
    return pygame.display.set_mode([width, height], pygame.SRCALPHA, 32), \
        pygame.Surface([ISCREEN_WIDTH, ISCREEN_HEIGHT], pygame.SRCALPHA, 32)

def flip_display(iscreen, screen):
    screen.blit(pygame.transform.scale(iscreen, \
        [ISCREEN_WIDTH * PIXEL_RATIO, ISCREEN_HEIGHT * PIXEL_RATIO]), \
        [SCREEN_X_OFFSET, SCREEN_Y_OFFSET])
    pygame.display.flip()

def main():
    quit = False
    pygame.init()
    screen, iscreen = setup_screen(SCREEN_WIDTH, SCREEN_HEIGHT)
    clock = pygame.time.Clock()

    main_map = hackmap("main")
    map_surface = main_map.draw()

    while not quit:
        time_passed = clock.tick(50)

        for event in pygame.event.get():
            if event.type == pygame.QUIT: quit = True
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_q: pygame.event.post(pygame.event.Event(pygame.QUIT))

        iscreen.blit(map_surface, [0, 0])
        flip_display(iscreen, screen)

    sys.exit()

main()
